In [2]:
import dgl
import torch
g = dgl.load_graphs("./intermediate_data/grapj_test.bin")
g = g[0][0]
print(g)

/home/dorian/.conda/envs/mntd/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Graph(num_nodes=91, num_edges=1674,
      ndata_schemes={'bias': Scheme(shape=(1, 512), dtype=torch.float32), 'pooling': Scheme(shape=(5,), dtype=torch.int64), 'params': Scheme(shape=(3, 2), dtype=torch.int64), 'node_size': Scheme(shape=(2,), dtype=torch.int64), 'bias_size': Scheme(shape=(2,), dtype=torch.int64), 'layer': Scheme(shape=(), dtype=torch.int64), 'tag': Scheme(shape=(), dtype=torch.int64), 'x': Scheme(shape=(512, 512), dtype=torch.float32)}
      edata_schemes={})


In [7]:
def conv(input, in_size, w, kernel_size, stride,):
    pass
def maxpooling():
    pass
# get src node feature
def message(edges):
    print("This is message function:")
    # print({'pre': edges.src['x']})
    return {'pre': edges.src['x']}
# compute received feature using mailbox
def reduce(nodes):
    # input layer, get image feature
    input_layer_mask = nodes.data['tag'] == 0
    conv_layer_mask = nodes.data['tag'] == 1
    concat_layer_mask = nodes.data['tag'] == 2
    fc_layer_mask = nodes.data['tag'] == 3

    # nodes.data['t'] = conv(image, kernel_weight, kernel_size, stride, padding)
    # nodes.data['t'] = maxpooling(nodes.data['t'], actual_size, kernel_size, stride, padding, dilation, ceil_mode)
    print("This is reduce function:")
    # print(nodes.mailbox['pre'])
    return {'h':nodes.data['x']}

In [8]:
g.update_all(message, reduce)

This is message function:
This is reduce function:
This is reduce function:
This is reduce function:
This is reduce function:


In [9]:
from utils_gnn import unpadding
row, col = g.ndata['node_size'][0]
# get actural kernel data
weight = unpadding(g.ndata['x'][0], int(row), int(col))
# add channel
print(weight)
weight = weight.unsqueeze(0).unsqueeze(0)
print(weight.size())
print(weight)

254 253 254 253
tensor([[-0.1224, -0.0953, -0.0025,  0.1096, -0.1517],
        [-0.1580, -0.1656,  0.0306,  0.1967,  0.2402],
        [-0.2434,  0.0711, -0.0533, -0.1392, -0.1160],
        [ 0.1162, -0.1471,  0.2129,  0.2059, -0.1470],
        [ 0.0543,  0.0874,  0.1545, -0.1643,  0.0806]])
torch.Size([1, 1, 5, 5])
tensor([[[[-0.1224, -0.0953, -0.0025,  0.1096, -0.1517],
          [-0.1580, -0.1656,  0.0306,  0.1967,  0.2402],
          [-0.2434,  0.0711, -0.0533, -0.1392, -0.1160],
          [ 0.1162, -0.1471,  0.2129,  0.2059, -0.1470],
          [ 0.0543,  0.0874,  0.1545, -0.1643,  0.0806]]]])


In [10]:
def cnn_forward_on_node(input):
    pass
relu = torch.nn.functional.relu
conv = torch.nn.Conv2d(1, 1, kernel_size=5, stride=1, padding=2)
print(conv.weight.data.size())
print(conv.weight.data)
conv.weight.data = weight
print(conv.weight.data)
max_pool = torch.nn.MaxPool2d(kernel_size=2, stride=2)

torch.Size([1, 1, 5, 5])
tensor([[[[-0.1932,  0.1673,  0.1722,  0.0167, -0.0647],
          [ 0.1359, -0.1465, -0.0194, -0.1681, -0.1491],
          [-0.0722,  0.0318, -0.0720, -0.1175, -0.0169],
          [-0.1413,  0.0290, -0.0581, -0.1793, -0.0227],
          [ 0.1407, -0.1191, -0.1375, -0.0848, -0.0310]]]])
tensor([[[[-0.1224, -0.0953, -0.0025,  0.1096, -0.1517],
          [-0.1580, -0.1656,  0.0306,  0.1967,  0.2402],
          [-0.2434,  0.0711, -0.0533, -0.1392, -0.1160],
          [ 0.1162, -0.1471,  0.2129,  0.2059, -0.1470],
          [ 0.0543,  0.0874,  0.1545, -0.1643,  0.0806]]]])


In [ ]:
conv()